/**
 * mm-api-client
 * Money Mommy API Explorer.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: towyuan@outlook.com
 *
 * NOTE: This library is auto generated by the Open API Codegen program.
 * https://github.com/taoyuan/generator-oac.git
 * Do not edit the class manually.
 *
 */

const utils = require('./_utils');

/*jshint -W069 */
/**
 * @class Container
 * @alias module:api/Container
 * @param {Requestor} [requestor] - The project domain or options object. If object, see the object's optional properties.
 */
class Container {
  constructor(requestor) {
    this.requestor = requestor;
  }
  /**
   * 
   *
   * @method
   * @path [GET] /Containers
   * @name Container#getContainers
   * @param {function} [cb] - Callback function
   */
  getContainers(cb) {

    const req = {
      method: 'GET',
      headers: {}
    };

    req.headers['Accept'] = 'application/json';

    const path = '/Containers';

    return this.requestor.request(path, req).then(function(result) {
      if (!cb) return result;
      cb(result);
    }, function(err) {
      if (!cb) throw err;
      cb(null, err);
    });
  }
  /**
   * 
   *
   * @method
   * @path [POST] /Containers
   * @name Container#createContainer
   * @param {object|function|*} [opts] - Optional params
   * @param {object} [opts.options] - options
   * @param {function} [cb] - Callback function
   */
  createContainer(opts, cb) {
    if (typeof opts === 'function') {
      cb = opts;
      opts = null;
    }
    opts = opts || {};

    const req = {
      method: 'POST',
      headers: {}
    };

    req.headers['Accept'] = 'application/json';

    req.data = opts['options'];

    const path = '/Containers';

    return this.requestor.request(path, req).then(function(result) {
      if (!cb) return result;
      cb(result);
    }, function(err) {
      if (!cb) throw err;
      cb(null, err);
    });
  }
}

module.exports = Container;